# -*- coding: utf-8 -*-
"""MLLab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10a1Toj2nbr7pT_jffIbWld61G_wrAJlO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

df = pd.read_csv('/content/drive/MyDrive/ML /Sheet3.csv')

df.head()

df

X = df[['AREA']]
y = df['PRICE(LAKH)']
model = LinearRegression()
model.fit(X, y)

from google.colab import drive
drive.mount('/content/drive')

plt.scatter(df['AREA'], df['PRICE(LAKH)'], color='blue')
plt.plot(X, model.predict(X), color='red')
plt.title('Area vs Price')
plt.xlabel('Area')
plt.ylabel('Price')
plt.show()

y_pred = model.predict(X)

new_area = 750
predicted_price = model.predict([[new_area]])
print(f"The price  {new_area}sq feet {predicted_price[0]} LAKH")