# -*- coding: utf-8 -*-
"""Practical2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovCT3fZ8jLYtvK3eHp--4lv7DUTvOuho
"""

!pip install numpy pandas matplotlib seaborn
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
iris = load_iris()

iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

print(df.head())
print(df.info())
print(df.describe())
print(df['species'].value_counts())

df.hist(figsize=(10, 6), bins=20)
plt.suptitle('Histograms of Iris Feature Columns')
plt.show()

sns.pairplot(df, hue='species')
plt.suptitle('Pairplot of Iris feature',y=1.02)
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot( data=df,orient="h")
plt.suptitle('Boxplot of All featurea')
plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(df.iloc[:,:-1].corr(),annot=True,cmap='coolwarm')
plt.suptitle('Correlation Heatmap')
plt.show()

df.info()

print(num_classes)

print(iris.target_names)

print("rows:", df.shape[0])
print("columns:", df.shape[1])

print(df.isnull().sum())
print(df.shape)
df.columns